import uuid from 'uuid/v1';

export default [
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    slug: 'ekaterina-tankova',
    email: 'ekaterina.tankova@devias.io',
    avatar: '/images/avatars/avatar_2.png',
    spent: '500.00',
    currency: '$',
    type: 'Agency',
    projects: '1',
    rating: 5,
    location: 'West Virginia, USA'
  },
  {
    id: uuid(),
    name: 'Cao Yu',
    slug: 'cao-yu',
    email: 'cao.yu@devias.io',
    avatar: '/images/avatars/avatar_3.png',
    spent: '300.00',
    type: 'Freelancer',
    currency: '$',
    projects: '3',
    rating: 4.3,
    location: 'Bristow'
  },
  {
    id: uuid(),
    name: 'Alexa Richardson',
    slug: 'alexa-richardson',
    email: 'alexa.richardson@devias.io',
    avatar: '/images/avatars/avatar_4.png',
    spent: '2,600.00',
    type: 'Enterprise',
    currency: '$',
    projects: '0',
    rating: 4.5,
    location: 'Georgia, USA'
  },
  {
    id: uuid(),
    name: 'Anje Keizer',
    slug: 'anje-keizer',
    email: 'anje.keizer@devias.io',
    avatar: '/images/avatars/avatar_5.png',
    spent: '5,600.00',
    type: 'Enterprise',
    currency: '$',
    projects: '6',
    rating: 4,
    location: 'Ohio, USA'
  },
  {
    id: uuid(),
    name: 'Clarke Gillebert',
    slug: 'clarke-gillebert',
    email: 'clarke.gillebert@devias.io',
    avatar: '/images/avatars/avatar_6.png',
    spent: '500.00',
    type: 'Agency',
    currency: '$',
    projects: '1',
    rating: 3.5,
    location: 'Texas, USA'
  },
  {
    id: uuid(),
    name: 'Adam Denisov',
    slug: 'adam-denisov',
    email: 'adam.denisov@devias.io',
    avatar: '/images/avatars/avatar_7.png',
    spent: '5,230.00',
    type: 'Agency',
    currency: '$',
    projects: '0',
    rating: 3,
    location: 'California, USA'
  },
  {
    id: uuid(),
    name: 'Ava Gregoraci',
    slug: 'ava-gregoraci',
    email: 'ava.gregoraci@devias.io',
    avatar: '/images/avatars/avatar_8.png',
    spent: '300.00',
    type: 'Freelancer',
    currency: '$',
    projects: '0',
    rating: 4,
    location: 'California, USA'
  },
  {
    id: uuid(),
    name: 'Emilee Simchenko',
    slug: 'emilee-simchenko',
    email: 'emilee.simchenko@devias.io',
    avatar: '/images/avatars/avatar_9.png',
    spent: '100.00',
    type: 'Agency',
    currency: '$',
    projects: '4',
    rating: 4.5,
    location: 'Nevada, USA'
  },
  {
    id: uuid(),
    name: 'Kwak Seong-Min',
    slug: 'kwak-seong-min',
    email: 'kwak.seong.min@devias.io',
    avatar: '/images/avatars/avatar_10.png',
    spent: '1,000.00',
    type: 'Freelancer',
    currency: '$',
    projects: '2',
    rating: 5,
    location: 'Michigan, USA'
  },
  {
    id: uuid(),
    name: 'Shen Zhi',
    slug: 'shen-zhi',
    email: 'shen.zhi@devias.io',
    avatar: '/images/avatars/avatar_11.png',
    spent: '2,300.00',
    type: 'Agency',
    currency: '$',
    projects: '0',
    rating: 3.9,
    location: 'Utah, USA'
  },
  {
    id: uuid(),
    name: 'Merrile Burgett',
    slug: 'merrile-burgett',
    email: 'merrile.burgett@devias.io',
    avatar: '/images/avatars/avatar_12.png',
    spent: '200.00',
    type: 'Enterprise',
    currency: '$',
    projects: '7',
    rating: 4.2,
    location: 'Utah, USA'
  }
];
